name: material_state_builder
description: A widget that offers the material states and its corresponding controller to a material widget.
version: 0.0.1
repository: https://github.com/Abel1027/material_state_builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
